### ISSUE TITLE
Blue Orion is making an API that will be like "Stripe for Stellar"

### ISSUE THREAD

**Issue by lukecarriere** [stellardevdigest/featured_project_dropbox#1]
Hello and thanks for writing issue #0 of the Stellar Dev Digest. 
I'm writing to apply to be highlighted as an exciting application from the Stellar ecosystem. I would appreciate if you would feature our project: blueorion.cc
We have a live noncustodial wallet with additional functions like:
- Timed transactions, 
- MultiSend
- Proof of Existence (document fingerprinting with hash on stellar blockchain)
- Subscriptions

You can test our testnet and earn XLM and SMART tokens (our own token) for sharing your feedback. Read more about that program here: https://www.reddit.com/r/BlueOrion/comments/bsmajk/2019_earn_lumens_by_testing/

Additionally we are participating in SCF to build an API. Our open API will feature: 
- future date payment scheduling
- mass payments to multiple addresses
- auto recurring subscription billing
Read more about our SCF proposal here: https://galactictalk.org/d/1946-timed-transactions-api-schedule-payments-on-the-stellar-network
Thanks,
Luke
Co-Founder

**Comment by robertDurst** [comment]
Thank you very much for the submission. Looks great. Any chance you could fill out the [submission template](https://github.com/stellardevdigest/featured_project_dropbox/issues/new/choose) I just setup? Need an example submission :)

**Comment by lukecarriere** [comment]
@robertDurst - my team has done so, here: https://github.com/stellardevdigest/featured_project_dropbox/issues/2

**Comment by robertDurst** [comment]
Awesome, thanks. Closing this
