### ISSUE TITLE
Timed Transactions API - Schedule payments on the Stellar network!

### ISSUE THREAD

**Issue by blueskytoday** [stellardevdigest/featured_project_dropbox#2]
# Stellar Dev Digest Application Feature Submission

![alt text](https://blueorion.cc/images/timedtransactions-header.png "")

**Project Name:** Timed Transactions API - Schedule payments on the Stellar network!

**Project Authors:** Hans Woppmann, Luke Carriere, Peter Pansegrau

**Brief Project Description:** Our project’s mission is to accelerate development timelines and to ease implementation of the Stellar network services. This is achived by creating a second layer infrastructure with out-of-the-box API services designed for the most common payments use cases. We will begin with timed and multiple transactions.

**We are looking for developers:** We are looking for tester. See more details on [reddit](https://www.reddit.com/r/BlueOrion/) 

**This is not an ICO:** No, this is no ICO!

**Relevant Links:**
* [GalaticTalk](https://galactictalk.org/d/1946-timed-transactions-api-schedule-payments-on-the-stellar-network)
* [Website](https://blueorion.cc/timedtransactions)
* github site in progress

**Comment by robertDurst** [comment]
Congrats! You are the featured project of Issue 1!
