### ISSUE TITLE
SwPlug

### ISSUE THREAD

**Issue by slideloft** [stellardevdigest/featured_project_dropbox#3]
# Stellar Dev Digest Application Feature Submission

![Screenshot 2019-06-10 at 12 13 12](https://user-images.githubusercontent.com/2800122/59192062-2fc11f00-8b79-11e9-8330-0684c645e338.png)

**Project Name:** SwPlug

**Project Authors:** Gbolahan Onadeko

**Brief Project Description:** Swplug plugin and Widget makes it easy to accept payments for goods and service without having to write a single line of code, it is as simple as plug and play, Swplug is valuable to the Stellar Ecosystem because it is a real use case of accepting payment and enable frictionless transaction between merchant and customer, No third party charge apart from the network tx charge by the Stellar Blockchain and it is totally non custodial.
Swplug makes use of the Stellar Blockchain by searching through the Stellar ledger for generated memo to confirm payment and also providing the merchant and customer email feedback of payment and link to the stellar ledger. It is currently available for Wordpress user via Woocommerce , and also as widget for any website type.

**This is not an ICO:** Not an ICO

**Relevant Links:**
* [Github]()
* [GalaticTalk](https://galactictalk.org/d/1906-swplug)
* [Website](https://swplug.com/)

**Comment by robertDurst** [comment]
Congrats, you're the featured app of week 1!
