### ISSUE TITLE
0rora - Stellar Payment Manager

### ISSUE THREAD

**Issue by Synesso** [stellardevdigest/featured_project_dropbox#4]
# Stellar Dev Digest Application Feature Submission

![Screen Shot 2019-06-13 at 11 22 16 AM](https://user-images.githubusercontent.com/21859/59396773-90e13080-8dcd-11e9-9bd1-0d4ebfd6dfc5.png)

**Project Name:** 0rora - Stellar Payment Manager

**Project Authors:** [Jem & Chen Mawson](https://keybase.io/jem)

**Brief Project Description:** 

0rora is a self-hosted solution for easily making, scheduling (and editing and responding to) Stellar payments. The goal of 0rora is to become a full-featured payment integration and management hub, where payments can flow from upstream systems or user entry, be warehoused, batched, netted, held for authorization and submitted with self-repair and retries.

At this stage it supports bulk, scheduled payments via CSV upload and is suitable for parties who wish to schedule & issue large volumes of payments efficiently. Payments made and scheduled can be viewed via the web app.

**We are looking for developers:** 

0rora is in [active development](https://github.com/0rora/0rora/issues). We are looking for contributors to help build out the product. The technologies used are:

- Playframework
- Akka
- Bulma
- Docker
- Postgres

Both technical and non technical contributors are warmly welcomed. Help is needed in all aspects, so please get in touch.

**This is not an ICO:** This is absolutely not an ICO.

**Relevant Links:**
* [Github](https://github.com/0rora/0rora)
* [GalaticTalk](https://galactictalk.org/d/1986-0rora-stellar-payment-manager)
* [Website](http://0rora.com/)

**Comment by robertDurst** [comment]
Congrats, you are the winner of the week!

**Comment by jpkane** [comment]
Cool. 

Keep up the great work on the StellarDevDigest!
