### ISSUE TITLE
Astrograph — an open-source GraphQL server for Stellar

### ISSUE THREAD

**Issue by nebolsin** [stellardevdigest/featured_project_dropbox#5]
# Stellar Dev Digest Application Feature Submission

<img src="https://user-images.githubusercontent.com/10788/59400065-ce7a9500-8d9e-11e9-80c7-fbee6e1cb9d1.png" align="right" width="200" />

**Project Name:** Astrograph

**Project Authors:** @nebolsin, @gzigzigzeo, @charlie-wasp 

**Brief Project Description:** Astrograph is the client-facing GraphQL server for the Stellar ecosystem. It is quite similar to Horizon, except that instead of exposing RESTful API, it provides a single endpoint to explore the Stellar network state and history using powerful GraphQL queries, while also allowing developers to add real-time capabilities to the apps faster and with less effort using reliable WebSocket-based subscriptions.

**We are looking for developers:** if you're building a Stellar-based product, we invite you to evaluate Astrograph and see if you can benefit from GraphQL’s flexibility and ease of use. In case you encounter a bug, want to extend Astrograph's schema with new fields or introduce some specific queries, filters or subscriptions  — please let us know by [raising an issue on Github](https://github.com/astroband/astrograph/issues/). 

**This is not an ICO:** definitely not, it's an open-source project targeting developers (but we participate in SCF right now)

**Relevant Links:**
* [Github](https://github.com/astroband/astrograph)
* [GalaticTalk](https://galactictalk.org/d/1911-astrograph)
* [Website](https://astrograph.io)

**Comment by robertDurst** [comment]
Congrats -- you are the app of the week!
