### ISSUE TITLE
Equilibre.io

### ISSUE THREAD

**Issue by MisterTicot** [stellardevdigest/featured_project_dropbox#6]
# Stellar Dev Digest Application Feature Submission

![](https://cdn-images-1.medium.com/max/936/1*3tkPlLF3VzdSEXfX7KZf8w.png)

**Project Name:** Equilibre.io

**Project Authors:** MisterTicot

**Brief Project Description:**
Equilibre.io is a portfolio balancer that runs on the Stellar Decentralized Exchange. It is a convenient trading tool to manage long-term positions.

Regularly balancing an investment portfolio is known to boost its performances, providing you choose wisely the assets to bet on. Equilibre.io also lets you spread your positions over several anchors, for better fund safety.

**We are looking for translators:**
https://github.com/cosmic-plus/webapp-equilibre-io/blob/master/CONTRIBUTE.md

**This is not an ICO:** No

**Relevant Links:**
* [Github](https://github.com/cosmic-plus/webapp-equilibre-io)
* [GalaticTalk](https://galactictalk.org/d/1969-equilibre-io-a-portfolio-balancer-for-stellar)
* [Website](https://equilibre.io)

**Comment by robertDurst** [comment]
Congrats you are the featured app of the week!
